name: CCW Extension Deployment
description: Deploy Extension To CCW
branding:
  icon: upload-cloud
  color: blue
inputs:
  file:
    description: The Extension file you want to deploy
    default: dist/index.js
    required: true
  project-oid:
    description: the project oid
    required: true
  token:
    description: ccw token
    required: true
runs:
  using: node24
  main: dist/index.cjs
